server:
  port: ${PORT_SERVER}
---
springbootwebfluxjjwt:
  password:
    encoder:
      secret: ${SECRET}
      iteration: ${ITERATION}
      keylength: ${KEY_LENGTH} 
---
spring:
  profiles: default
  data:
    mongodb:
        uri: ${CONEXION_MONGO}/hondurasdb
       
